[tool.isort]
multi_line_output = 3
line_length = 88
include_trailing_comma = true

[tool.black]
line_length = 88

[tool.docformatter]
black = true
close-quotes-on-newline = true
pre-summary-newline = true

[tool.interrogate]
ignore-init-module = true
ignore-module = true
exclude = ["data", "bin"]
